### ISSUE TITLE
Lost cursor

### ISSUE THREAD

**Issue by vega-bihu** [iamcco/coc-actions#4] opened 2020-01-22 07:00 UTC
I was always lost my cursor after call the command 'actions.open' and showed the menu prompt.
How can i fixed it?

**Comment by iamcco** [comment] 2020-01-27 08:03
I had added `coc-actions.hideCursor: false` option to control this behavior.

**Comment by webdavis** [comment] 2020-03-09 06:26
Is there anyways to fix this without having to set `coc-actions.hideCursor: false`?

**Comment by iamcco** [comment] 2020-03-09 06:36
@webdavis I don't know what you mean by fix this? It's not a bug if you do not want this feature just set `coc-actions.hideCursor: false`

**Comment by webdavis** [comment] 2020-03-09 08:15
Oh I see. I read the OP wrong. I must have a bug then. When I set `coc-actions.hideCursor = true` I lose the cursor permanently upon exiting the coc-actions floating window. Shortly after Neovim crashes and I am taken back into my terminal where the cursor is still missing.

**Comment by iamcco** [comment] 2020-03-09 09:22
@webdavis What's your neovim version?

**Comment by webdavis** [comment] 2020-03-09 16:27
```
NVIM v0.5.0-397-g96059d72e
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/gcc-5 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -Og -g -Wall
-Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow
-Wconversion -Wmissing-prototypes -Wvla -fstack-protector-strong -fno-common
-fdiagnostics -color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE
-DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3
-I/home/travis/build/neovim/bot-ci/build/neovim/build/config
-I/home/travis/build/neovim/bot-ci/build/neovim/src
-I/home/travis/build/neovim/bot-ci/build/neovim/.deps/usr/include
-I/usr/include -I/home/travis/build/neovim/bot-ci/build/neovim/build/src/nvim/auto
-I/home/travis/build/neovim/bot-ci/build/neovim/build/include
Compiled by travis@travis-job-13ebc8c2-4f6f-45b7-ad53-0dc3d8813d5f

Features: +acl +iconv +tui
```

**Comment by iamcco** [comment] 2020-03-10 09:05
@webdavis Upgrade to NVIM v0.5.0-nightly-325-g2b00d1d09 and can not reproduce the issue.

**Comment by webdavis** [comment] 2020-03-10 19:43
I upgraded neovim and I'm still getting the issue. When I run `verbose set guicursor?` I get:
```
  guicursor=n-v-c-sm:block,i-ci-ve:ver25,r-cr-o:hor20
        Last set from API client (channel id 3)
```
If I exit Neovim before it crashes I get the cursor back and I can reenter nvim and everything seems fine.

I have tested turning off all other plugins and the behavior still happens.

Do you have any other ideas about what could be causing this to happen for me?

**Comment by iamcco** [comment] 2020-03-11 07:36
I have no idea.

**Comment by vn-ki** [comment] 2020-04-19 10:53
I have the same issue. I'm on nvim master as well.

**Comment by lucasdf** [comment] 2020-04-26 20:10
I am having this problem as well. I had the same issue with `CocList` recently, and I have solved it by using `g:coc_disable_transparent_cursor`, which recently added to coc after this issue was opened https://github.com/neoclide/coc.nvim/issues/1775 . Might give some clue about what is going on.

**Comment by iamcco** [comment] 2020-04-27 03:26
@lucasdf  use `"coc-actions.hideCursor": false` to disable this feature.

**Comment by szbergeron** [comment] 2020-05-02 05:08
Am dealing with this as well, setting coc-actions.hideCursor to false does not seem to fix it for me, weirdly enough

*edit: initially accidentally put "setting to true" rather than setting to false

**Comment by NullVoxPopuli** [comment] 2020-05-17 22:41
how do you debug stuff not working? for example:
I'm trying to implement this in https://github.com/NullVoxPopuli/coc-ember/pull/31
https://twitter.com/vaier/status/1261984082361290753
(tldr: just select range, extract file)

I think what's getting lost, is that in the VSCode version, there is a prompt for file name, but in my coc extension, there is no prompt

**Comment by iamcco** [comment] 2020-05-18 02:35
@NullVoxPopuli print log

**Comment by NullVoxPopuli** [comment] 2020-05-18 03:16
turned out to maybe be unrelated?
```ts
  context.subscriptions.push(
    commands.registerCommand(
      COMMANDS.GET_USER_INPUT,
      async (opts, callbackName, tail) => {
        try {
          let name = await workspace.requestInput('Component Name');
          let document = (await workspace.getCurrentState()).document;

          console.info(name);
          console.info(document);
          await commands.executeCommand(callbackName, document, name, tail);
        } catch (e) {
          workspace.showMessage(e.toString(), 'error');
        }
      }
    )
  );
```
I think I'm passing the wrong document, so I need to ask the language-server person

**Comment by iamcco** [comment] 2020-06-29 03:06
Close, it should be fixed according to https://github.com/iamcco/coc-actions/pull/16. Feel free to reopen if the issue still exists.

**Closed as completed by iamcco** 2020-06-29 03:06 UTC
Labels: help wanted
